### ISSUE TITLE
Is there a way to reorder blocks on smaller sizes?

### ISSUE THREAD

**Issue by ivanjuras** [thoughtbot/neat#313]
I was wondering if there is a way to reorder the blocks on smaller sizes. Let's say that I have a tablet breakpoint where the grid has 8 columns and every block stacks on top of each other.

Is there a way to reverse the order so that the block that would otherwise be on top now goes to the bottom?

**Comment by whmii** [comment]
You are able to use [shift](http://thoughtbot.github.io/neat-docs/latest/#shift) to move things latteraly. This cal do things like move a coloumn to the right on a small screen but move it to the left on a large one. Unfortunately vertically reordering them is not possible.

This can be achieved with [flexbox](http://css-tricks.com/snippets/css/a-guide-to-flexbox/) how ever, which can be a viable option depending on your browser support needs.

**Comment by wardpenney** [comment]
Yes @ivanjuras @whmii is correct, you can put the markup (HTML) in the order you want it to appear when everything is 100% width. Then use shift to reverse that order at higher breakpoints. This would be a good question for help from Stack Overflow also http://stackoverflow.com/questions/tagged/neat . I'm going to close the issue here. Thanks!
