### ISSUE TITLE
Parent Columns number

### ISSUE THREAD

**Issue by renatodex** [thoughtbot/neat#320]
Hi guys,

How i do it using Neat:

```
  .element {
    @include span-columns(6);

   .nested-element {
     @include span-columns(2 of parent-column());
   }
```

Where "parent-column()" should be eq 6.

What we wanted to do is create a generic "nested span-column" CSS class like "nested_5" that could automaticaly detect the column size of parent element and aply the correct width.
Example: If parent element had 6 columns, so "nested_5" should do: 

```
@include span-columns(5 of 6);
```

Thanks!

]['s

**Comment by corysimmons** [comment]
I don't think it's possible to detect what column has been used in a parent container. Preprocessors can't "step up" like that.

**Comment by wardpenney** [comment]
Yes @corysimmons is right. I did try a small experiment once that attempted to do that by keeping lists and assuming node depth. The problem is you only have procedural execution order to work with. So, it becomes dependent the order of declarations in the source file, and it becomes pretty fragile.
