### ISSUE TITLE
Example on home page of Neat

### ISSUE THREAD

**Issue by gavrochelegnou** [thoughtbot/neat#337]
The example on the home page of your website is using `aside` and `article` tags where the semantics would suggest using `<hx>` and `<p>` tags (or `article` but it's a little bit far fetched). `aside` should only be used for content that is "secondary" like a sidebar ... whereas it is used here for titles.

It would be great that examples also respect best practices of the underlying languages.

So your example could look like : 
```html
<section>
  <h2>What is it about?</h2>
  <p>Neat is an open source semantic grid framework built on top of Sass and Bourbon…</p>
</section>
```
```sass
section {
  @include outer-container;
  h2 { @include span-columns(3); }
  p { @include span-columns(9); }
}
```

Or you could wrap the <p> in a div/article if you have multiples <p> in a <section> but the whole list being the article i would suggest a div.

Thanks for the good work !

**Comment by odraencoded** [comment]
I don't even use this thing and I was going to post this issue.

It's really dangerous code. Someone might see it and use as an example, but the example is wrong, which means wrong semantic markup gets propogated.

If semantic markup is used in a way different of the standard, it becomes pointless.

*For example*, I could make a plugin for chrome that hid all asides in a page, because aside content is only **loosely related** so most of the time I wouldn't care about it anyway. But if people put into asides content that is not only **closely related**, but even **labels** other content, my plugin would do more harm than good.

**Comment by t--o** [comment]
Same thoughts here. Came here to voice my concern about this – funny to see there are two other participants already… 
The contents in the <aside> tag on the homepage should rather be headings. It's really misleading for developers who are new to HTML5

**Comment by maxx1128** [comment]
I've read the code on the Neat site almost a dozen times and only just noticed this, and while it's small I do agree that it's worth changing. I'd almost say that all the sections should be in a single section tag, each one being an article tag and then containing the h2 and p tags.

```
<section>
     <article>
          <h2>Headline</h2>
          <p>Paragraph Copy</p>
     </article>
     <article>
          <h2>Headline</h2>
          <p>Paragraph Copy</p>
     </article>
</section>
```

**Comment by whmii** [comment]
Thanks for spotting this! We've updated the page in https://github.com/thoughtbot/neat/pull/454
