### ISSUE TITLE
Fixing display deprecation warning not intuitive or helpful

### ISSUE THREAD

**Issue by jschneier** [thoughtbot/neat#338]
Hey I'm using neat 1.7.1 and am hitting [this warning](https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/grid/_row.scss#L39).

The message says it will be deprecated in favor of the `display` mixin which I assume refers to Bourbon's. However, all that Bourbon's display mixin does for non-flexbox is set `display: $display` which is not at all what happens when I `@include row(table)`. I also tried using `@include display-context(table)` but that also produces different CSS/display. Do you have any suggestions or guidelines on the correct way to fix that warning?

**Comment by aarontropy** [comment]
+1 This is doubly confusing because the documentation only explains the "old" way of doing things.

**Comment by MarkPochert** [comment]
+1 I dont know how i can fix this warning in my code.

**Comment by jermspeaks** [comment]
+1 Would like to know if this is solved from updating to the latest version.

**Comment by Sxderp** [comment]
I also have this problem.
I'm using Neat 1.7.2.

Additionally, doing the following also produces an error.
```
@include display(table) {
    text-align
}
```
`error ./ncg.scss (Line 179: Mixin "display" does not accept a content block.)`

This doesn't make any sense..? Why would it say to use a block in the previous error and then not accept a block?

**Comment by puresamari** [comment]
+1 hello guys,

i researched a little on that matter because i had the same problem and i found the problem and a kind of workaround

at the file __app/assets/stylesheets/grid/_row.scss__ neat is only checking on the parameter parsed through the row() mixin:

 `@if $display == table {`

after a quick view on the display-context-file __app/assets/stylesheets/grid/_display-context.scss__ i found the global variable __$container-display-table__ which carries a bool value if $display equals 'table'.

so i added on the row-file 

`@if $display == table or $container-display-table {`

this works perfectly fine now but it should be somehow implemented in the neat-plugin itself because the warning message on row(table) gives me a headache 

hope i helped

**Comment by whmii** [comment]
Posting a quick update here. I am working on a PR to silence these errors. Originally we had planned on depreciating the `reset-display()` mixin in favor of a more generic and controlable `display()` mixin. However, this will no longer be the case in the immediate future.

2.0 will represent a larger set of changes that will render this mixin irrelevant, so a depreciation warning would be a little silly.

Thanks for file this issue @jschneier @aarontropy @Sxderp and @puresamari. Apologies it took so long in addressing this. 🙇  Issues like this will be more swiftly addressed in the future.

**Comment by tysongach** [comment]
Couple things:

1. I _think_ that `@warn` message simply has a typo and `display()` should be `display-context()`.
2. The reason I think this typo was made is because the `display-context()` mixin _used_ to be named simply `display`. It was renamed because it conflicted with Bourbon’s `display` mixin.
  - Here’s when the `display` mixin was introduced: https://github.com/thoughtbot/neat/commit/4eb67b8e680a85b1dae3fadf51ff2cfe99a4c2b6
  - And here’s when it was renamed to `display-context`: https://github.com/thoughtbot/neat/commit/7a66600c7e3df75d5e23c21816ba48b5a5d6d0fb

**Comment by whmii** [comment]
Ah, that makes more sense.

**Comment by whmii** [comment]
@jschneier this has been fixed on `master`. I will cut a new version this afternoon.

https://github.com/thoughtbot/neat/pull/456

**Comment by zinkkrysty** [comment]
Would appreciate it if this would be included in an official version.

**Comment by dcalhoun** [comment]
@whmii it'd be great to see this change published in a `1.x.x` release.
