### ISSUE TITLE
Is it suggested to use max-width instead of min-width?

### ISSUE THREAD

**Issue by CoralSilver** [thoughtbot/neat#363]
Neat seams to use max-width for the breakpoints in its examples.  Is this the suggested usage?  If so, is there a reason it was not designed to be mobile-first?  What are the disadvantages to using it with min-width?

**Comment by davidbarker** [comment]
I'm also curious about this.

**Comment by tysongach** [comment]
Truthfully, the [examples](http://neat.bourbon.io/examples/) page is a bit out of date…but I think the `min-width` vs. `max-width` usage really just boils down to the project needs. There’s no one right way or wrong way. It depends on the project and how you like to work.

It’s probably worth noting that Neat does have a [`default-feature` variable](http://thoughtbot.github.io/neat-docs/latest/#default-feature). So whichever way you decide to work—`min` or `max`—you can set it globally with that (it defaults to `min-width`).

Hope that helps!

**Comment by jpdevries** [comment]
While there is no right or wrong way, polyfills like [respond](https://github.com/scottjehl/Respond#usage-instructions) instruct users to write CSS mobile first and then use media queries to adapt layout all the way up to desktop:

```css
@media screen and (min-width: 480px) {
    /* ...styles for 480px and up go here */
}
```

Personally I think this is kind of nice because even if you omit the polyfill, ie8 will get a degraded one column (mobile) layout.
