### ISSUE TITLE
Is there going to be a Neat 2.0

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/neat#382]
Hello
While other frameworks(Susy, Bootstrap, Foundation) are heading towards integrating flexbox and giving developers a choice I was wondering where Neat is heading - is there going to be a new version anytime soon - what are the plans as to Neat?

**Comment by ivanjuras** [comment]
I'd like to know that too.

**Comment by wardpenney** [comment]
I like the option of being able to make a grid with flexbox. The primary benefits would be:

* Easy vertical align
* Easy column reordering
* Easy equal-height columns

I would like the option to use a classic grid when I want, and a flex grid when I want–the latter possible being containable within the former. 

Also, since we're talking about a possible 2.0 in general, here's some things I really want to see:

* Being able to re-define grid container widths, columns, and gutters on the fly.
* Simple one-line `@import` of neat (remove need to import `neat_helpers` in order to declare breakpoints.)
* Make the source code lighter to read and easier to maintain by factoring out different `span-columns` display modes into separate methods (rather than configurable methods that access global variables). 
* Separate [rendering and non-rendering Sass](https://robots.thoughtbot.com/separate-rendering-sass-from-non-rendering-sass) for easier maintenance. 
* Include optional rendered classes and grid helpers, if desired, through a second `@import "neat_grid_classes"` or something like that.

The phrase I have been using is something like "Neat Lite" or something meant to mean it is:

* Lightweight to use, and not-conflicting with anything you have in place already
* Simple to understand and make PR's against
* Good useful layout examples, including advanced ones

thoughts?

**Comment by bjornpost** [comment]
:+1: on a flexbox version of Neat

**Comment by mmjaeger** [comment]
looking for alternatives to Neat - doesn't seem anybody watching here

**Comment by wardpenney** [comment]
@mmjaeger just wondering, what are you looking to do with Flexbox for your page layout? Any particular feature you need? I outlined a couple above; are those motivating you?

**Comment by mmjaeger** [comment]
I think you summed it up nicely in your previous post - bootstrap 4 and foundation 6 both support flex box, even for the overall layout of the page but also inline columns, galleries, etc.

**Comment by jklegseth** [comment]
@wardpenney +1 on your ideas. Well thought out and stated.

**Comment by codethebeard** [comment]
:+1: I would LOVE to see Flexbox support in this.

**Comment by jasonmelgoza** [comment]
+1 :+1:

**Comment by jpdevries** [comment]
> Include optional rendered classes and grid helpers, if desired, through a second @import "neat_grid_classes" or something like that.

I like this. Seems like given Neat's "silent" reputation though maybe it should be out of the core with some like a neat-helpers include.

**Comment by tangst** [comment]
+1

The thing I like about flexbox is that flexbox nests.  You can declare a new flexbox on a child element, and have that element's children have new flex ratios.  

Old browsers that do not support flexbox are becoming a smaller share of the internet space.  Microsoft  announced end of life support for IE8, IE9, and IE10 on Windows 7 and 8, which strengthens the argument that a Flexbox option is desirable.

**Comment by mehlah** [comment]
I don't totally agree here (9 vs 1 :sweat_smile:).
Flexbox is described by the W3C as being intended for laying out UI elements, things like menu items, and. It’s not intended for laying out whole pages.
The reason it’s not intended for layout out whole pages, is that flexbox has a companion CSS module, the Grid Layout Module which is intended for layout. 
Grid Layout is considered to be the most appropriate technique for full page layouts.
Sadly Grid Layout has a very limited support http://caniuse.com/#feat=css-grid

Also, note that Flexbox will always be slower than regular block layout (without floats) because Flexbox is multi-pass. 
> That said, if you can get away with it, regular block layout (non-float), will usually be as fast or faster than new flexbox since it’s always single-pass. But new flexbox should be faster than using tables or writing custom JS-base layout code.

(source https://developers.google.com/web/updates/2013/10/Flexbox-layout-isn-t-slow)

Don't compare Neat with Bootstrap or Foundation. Neat is a tool for building layouts, not a CSS framework for quick prototyping. As far as I know, Susy doesn't have (yet) a Flexbox support.

**Comment by tangst** [comment]
It's precisely because Grid Layout module is not widely supported that people will use Flexbox, regardless of its intended purposes.  The Table tag was not intended to be a layout element, but developers used it anyway, because nothing else really worked at the time.  To deny giving Bourbon Neat flexbox support and waiting for "proper" Grid support is simply allowing developers to look at other solutions.  Searching on Google for "flexbox layout" already yields many examples of using flexbox for layout. Expect developers to use whatever is at hand to make things work.

As it stands, I am not sure I can recommend Neat to developers, because Thoughtbot doesn't tell us what's going on.  There is no roadmap or other announcements.  I tried to contact their Twitter account, and nobody is answering.  Not saying anything for long periods of time gives the impression Neat is not a high priority.  If an open source project wants mass adoption, it at least needs to communicate what it intends to do or not do to the developers.

https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/

Yes, Susy doesn't have Flexbox either.  They also aren't communicating very much either.  Those are also reasons I'm not sure I can recommend it to other developers either.

**Comment by joshuaogle** [comment]
There has been some discussion and experimentation for what a "Neat 2.0" looks like, including how a Flexbox grid can/should be, but for the most part we're happy with how Neat works. We use it in client projects all the time and it works great. The experimentation mostly revolves around how to avoid some of the confusing parts like `omega` and support for nested grids.

I'm personally not convinced that Flexbox can/should be used over floats for general layout, but it's worth trying (so that makes 2 of us anyway, @mehlah), but I'd love to be proven wrong. As always, PRs and discussions around this are very welcome.

>  ... because Thoughtbot doesn't tell us what's going on.

There just hasn't been much to report yet. We're around (@wardpenney in this thread is at thoughtbot), and we will certainly post more when we have something we like and want to use.

**Comment by startupthekid** [comment]
I think neat is perfectly fine, I don't necessarily see the need for a major update. The only things I would change are:

- The ability to target multiple breakpoints:

```
@include media($tablet, $desktop) {...}
```

and that can be accomplished for now with a mixin:

```
@mixin multiple-media($queries...) {
  $loop-to: length($queries);
  $i: 1;
  @while $i <= $loop-to {
    $query: nth($queries, $i);
    @include media($query) {
      @content;
    }
    $i: $i + 1;
  }
}
```

- The ability to override neat variables within a specific nesting context/container

This issue is bigger on my list right now because there are some places where I would love to change `$gutter` but just within that container. Setting the gutter I need is really just a matter of setting the right margin but that leads to code smells since it's overriding what `span-columns` is already generating.

Other than those two (and maybe multiple grids and examples on how to include with webpack since that's popular now, glad to provide my config btw) I don't see the need for a major update to Neat. Like you @joshuaogle I'm not convinced that Flexbox is "better" but I'm also down for being proved wrong.

And @tangst you can complain all you wish but perhaps instead of berating the collaborators, maybe issue a PR? Even if it's not accepted, it's still great practice to become more advanced at writing layouts and sass.

> Expect developers to use whatever is at hand to make things work.
> gives the impression Neat is not a high priority

What about neat doesn't meet your needs? I've been using it for about 6 months now and I've haven't found a library that beats it. Even the things that it can't do are easy to work around. It's like the old adage, "If it ain't broke, don't fix it"

**Comment by tangst** [comment]
@joshuaogle : Thanks for replying to the thread and giving us an update.  Your post is exactly what I'm looking for in terms of communication from open source projects. It's a "we're still here, but no new updates planned yet, because of X, Y, and Z."

Since Neat is currently working for Thoughtbot as-is, that indicates that you're not in a rush to update it.  That's important to hear.  It does mean that Neat is on a long update cycle and prospective users can decide whether they want to use it or not.

If no decision has been made on a future version of Neat in 6 months to a year, but you're still using it without issues, I think a periodic "no news is good news" message to the public would be helpful.

@startupthekid : I am currently evaluating layout systems for my enterprise, but I don't have a specific use case to which to use Neat.  I can only go by what I was reading in the docs or trying to get Thoughtbot to reply to some queries (like my Twitter query which went unanswered).  Because the Github activity was low and there was no "no news is good news" message available until now, I was concerned Neat was being abandoned.  It's a pain to adopt an open source solution that becomes unsupported.  I wouldn't even attempt a PR if I didn't feel that the original collaborators were paying attention.  At least, now I know that the original collaborators are still here.

You may not like people complaining, but I think my complaint of a lack of communication from the original collaborators is a valid one.  There are a lot of open source projects that have become abandoned, so some periodic communication on the project page can help keep people in the loop.

**Comment by tangst** [comment]
Thank you to the person on the Bourbon Neat team who answered my question on Twitter!  Much appreciated!

**Comment by tysongach** [comment]
@tangst No problem! :wink: First day back after some travel. Happy new year!

**Comment by mmjaeger** [comment]
any news yet on a Neat flex box version??

**Comment by whmii** [comment]
@mmjaeger Neat 2.0 will be float based but will work seamlessly with floated containers. There is a v2.0.0 branch in development

**Comment by tysongach** [comment]
@whmii Did you mean _flex_ containers?

**Comment by whmii** [comment]
yes… yes I did.

**Comment by whmii** [comment]
**A brief update**: We have begun internal testing of the Neat 2.0 pre-alpha with promising results. At this time I would not recommend anyone use it for professional projects, I would encourage anyone who is interested it it to give it a whirl.

As with Neat 1.X there is a contrib section within the project that will allow you to quickly open up the test page using  Gulp.

While there are features we are still looking to add, the core way the grids are produced/calculated is decidedly different. The ultimate behavior is relatively the same but with some clear differences. Neat 2.0 now uses a `calc()` based system to determine the width of columns and will allow the system to write more different types of grids in less overall code.

One of the major pain points with the current 1.x code base is that its just too big. Neat 2.0 will represent a more consolidated project similar to the changes made in Bourbon 5.0.

**Comment by mmjaeger** [comment]
which of the 2.0 version should we try and play with - there is
2.0.0-neat-namespace, --parse-columns and 2.0.0 - the latest code changes
don't seem to be implemented yet into the flex-grid version??

On Thu, Jul 14, 2016 at 5:06 AM, Will H McMahan <notifications@github.com>
wrote:

> *A brief update*: We have begun internal testing of the Neat 2.0
> pre-alpha with promising results. At this time I would not recommend anyone
> use it for professional projects, I would encourage anyone who is
> interested it it to give it a whirl.
>
> As with Neat 1.X there is a contrib section within the project that will
> allow you to quickly open up the test page using Gulp.
>
> While there are features we are still looking to add, the core way the
> grids are produced/calculated is decidedly different. The ultimate behavior
> is relatively the same but with some clear differences. Neat 2.0 now uses a
> calc() based system to determine the width of columns and will allow the
> system to write more different types of grids in less overall code.
>
> One of the major pain points with the current 1.x code base is that its
> just too big. Neat 2.0 will represent a more consolidated project similar
> to the changes made in Bourbon 5.0.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/thoughtbot/neat/issues/382#issuecomment-232646896>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABe4lCOFX5w-9kmFDsUnwApyV2VstzUwks5qViZBgaJpZM4F-WCu>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by whmii** [comment]
@mmjaeger [neat-2.0.0](https://github.com/thoughtbot/neat/tree/neat-2.0.0) branch

A taged version has not been created yet (working on a couple of super cool final features) but I am looking to have a v2.0.0-alpha tagged version by mid-week. We are developing some improved documentation for it as well, but that wont be available until the beta has been released.

**Comment by whmii** [comment]
This has been an awesome thread. Since the core issue has been answered `"Is there going to be a Neat 2.0" == true` I am going to close this issue in favor of [https://github.com/thoughtbot/neat/issues/485]. 

Since a lot of this thread ended up as a discussion on "something something… flexbox", those interested can also check out [https://github.com/thoughtbot/neat/issues/483] which expands on some of these ideas and our decision to stick with floats for the core functionality.

Thank you to @wardpenney  @startupthekid @joshuaogle and @mehlah for making this such a great discussion. 👍 👍 👍 👍
