### ISSUE TITLE
Shift of -12 goes 100% plus one gutter too far

### ISSUE THREAD

**Issue by nickfmc** [thoughtbot/neat#413]
When I have a 3 column layout and I shift the order It pulls the one I shift by -12 by a gutters width too far. pulling it outside of the section container. 

http://codepen.io/anon/pen/pgBEgN?editors=110

**Comment by whmii** [comment]
1. @nickfmc thank you for making a code pen. It makes it sooooo much easier to debug. 👍 

2. The "extra margin" is caused by the `omega` on the 2nd col which removes its margin, their by pulling the third column over 1 gutter width which is then supplemented by the 1 gutter width that the `shift` accommodates for, making 2.
   Unfortunately, the `shift` mixin isn't very well suited for true reordering of columns. If it is a major issue I would just translate or relatively position the third column one `$gutter` to the right :S. I realize that super ghetto. We are working on a better alternative for an upcoming version.
