### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by mmjaeger** [thoughtbot/neat#483]
Don't see any flexbox grid anymore - as to the grid I was wondering why you're not using margin left and right on the column and a negative margin on the parent to compensate ??

**Comment by whmii** [comment]
Neat 2.0 was designed to be compatible with flexbox, Because of the way the grid properties are defined, flexbox can be added to the parent and then you are able to use flexbox in conjunction with Neat 2.0. As for why doesn't the whole system use flexbox, there is some discussion at https://github.com/thoughtbot/neat/pull/427

One of the larger hurtles in working with neat on larger codebases has been the use of omega and `nth-child` selectors. This causes a need for overly specific selectors that are difficult to override and debug. This and other caused us to rethink how the grid 'thinks' and instead of using margin right and nth child selectors, the grid instead uses margin left and determines its own location within the system. This also cut down on the overall code generated when the library is used. 

Thanks for bringing this up.

**Comment by mmjaeger** [comment]
I'm still wondering why you guys decided to go with a full left gutter instead of adding halve gutters to the left and the right and then negate the halve gutter on the parent/row to compensate. I don't see that you compensate for the left gutter on the parent so the content in the first column is actually not flush with the content before that's not in a column or do I miss something here.

**Comment by whmii** [comment]
Yes, it's an important distinction to make and possibly the greatest change between Neat 1.X and 2.X.

Neat 2.0 will have gutters on either side of all columns. creating a layout similar to the one pictured below:

<img width="1315" alt="screen shot 2016-07-18 at 10 46 48 am" src="https://cloud.githubusercontent.com/assets/2489247/16918841/48c3277c-4cd5-11e6-9be3-5c2a2977fea5.png">

In the example the container is dark grey and all columns are light. You can see that, distinct from 1.0, these columns are equally separated on either side. This structure has a few benefits: 

- It is very difficult to have a grid object break layout, an issue that is often due to how browsers handle their numerical rounding and one that has happend with relative frequency in 1.X
- It allows for a greater level of object independence as described in

  > …an object is responsible for positioning itself correctly in the grid as apposed to pushing its siblings away, placing them in the correct position. It's a bit of a mental switch but it allows objects a higher level of independence since they are able to position themselves… instead of relying on a preceding sibling.
- No nth child selectors are required to achieve a basic layout.
- Features like dynamically repositioning/reordering grid columns in ways that were not previously possible. issue: https://github.com/thoughtbot/neat/issues/413 new behavior: https://github.com/thoughtbot/neat/pull/481
- Gutters can now be defined in `rem`s, `em`s, `percentage`s, and pretty much any other unit which allows layouts to be defined by the user and not the library.

Collapsed columns will be added before the beta as described in https://github.com/thoughtbot/neat/issues/482 This will allow users to create columns that are 'flush against the sides', visually similar to Neat 1.X's implementation.

All in all, it is a series of tradeoffs, but i believe in these choices and that they will create a more flexible, reliable and scaleable system.
