### ISSUE TITLE
Grid-container and its max-width

### ISSUE THREAD

**Issue by nickngqs** [thoughtbot/neat#498]
Having a fun time play with the Neat 2.0 Grid, however since its fundamentally different from v1. I'm trying to wrap my head around on how the grid works.

About the grid-container. Different from v1, I found out that its container doesn't actually give a max-width. I'm guessing the right way is to add a max-width after your grid-container. But is there a reason for not including a default max-width. I tried declaring grid-media, but I guess that's just used for targeting responsive.

Seeing the grid-container mixin, the docs show this - without the (); But seeing the mixin, it seems to be able to take in arguments.

So i thought I could do this like in v1. But nothing happens I guess.
`.element {
  @include grid-container(1024px);
}`

In the docs
`.element {
  @include grid-container;
}`

**Comment by whmii** [comment]
In general, I have been tying to avoid situations where 1 setting equals to one line of code. As of now, there is no input to `grid-container` and it's really just a clearfix basically. The 'designed behavior' is that a user would follow this up with a `max-width: foo;`.

It may be that this is so counter people's expectations that we include it. I could be convinced, but my personal preference would be no.

@wardpenney thoughts?

**Comment by kgcreative** [comment]
So this is an old issue and probably moot, but I appreciate not having a max width explicitly set on grid containers. If I want to set a max width, I can do so explicitly.

**Comment by nickngqs** [comment]
I think it's okay if the max width is not explicitly set but wouldn't it be better if it allows us to?

So instead of having a default value in grid-container

Allow the option to do this 
```
@include grid-container(1024px)
```

Instead of doing this 
```
@include grid-container
max-width: 1024px
```

I do feel its much cleaner and easier to maintain as a one liner. What do you think about this?

**Comment by kgcreative** [comment]
I could take it or leave it. I've actually been setting max width on containers using calc and padding instead of max width. That allows me to have background images or colors that span the whole width, without emitting a second container (or wrapper), while still having constrained text, so in my case, I would very rarely use the built-in function. 

The second issue is for me, I want to vary max-width by breakpoint, so that means either using `@include grid-container($width)` inside each breakpoint, or just redeclaring max width on each media query (which is more dry, and cleaner).

Looking at bourbon 5 and neat 2.0, the philosophy seems to be moving toward simpler, cleaner, and more lightweight. Because of my own use cases, I actually ended up writing my own container mixin that includes calls `@include grid-container;` so, in my own case, it's `@include section-container(medium);` (or large, or small, which then has it's own width calculations on different breakpoints).

So, the very long and meandering answer is that for me, it's pretty moot, and it feels cleaner not to have that overhead, but ultimately it doesn't make that big of a difference (personally) to have the option to pass the mixin a value.

**Comment by nickngqs** [comment]
okay, you got me intrigued. So how, do you use calc and padding instead of max-width to have the constrained container without using a second container.

**Comment by kgcreative** [comment]
@nickngqs here you go: http://codepen.io/kgcreative/pen/ozPLLb?editors=1100

**Comment by whmii** [comment]
I have to side with @kgcreative here. Neat's purpose to do a series of calculations and output that a user would find it tedious, difficult or impossible. However, we've really tried to avoid situations in which a single perimeter results in single line of code that user could input without the assistance of the library. 

As KG described leaving this feature out actually gives the users more options and greater versatility system.

**Comment by digisavvy** [comment]
Just adding my voice to this discussion, even though it's closed. Today, I've struggled with a max-width issue, too. I tried the same things nickngqs did. But the fundamental differences between 1.x and 2x are at issue for me. This is definitely something to call out in future guides, in my opinion.

**Comment by tmatthews0020** [comment]
v2 docs say the grid-container outputs

>  clear: both;
>  content: "";
>  display: block;
> 

a simple way to have a set max-width that is centered would be ....

>  max-width: 1550px; (whatever you want) 
>  margin: 0 auto;
> 

with neat this would look liike 

> .container {
>    @include grid-container;
>    max-width: 1550px;
>    margin: 0 auto;
> }


hope this helps someone

**Comment by hendrikeng** [comment]
@digisavvy 

you could simply just add a media query to the element you want to keep within the container i.e. your container width is 1200 px:

```scss
.element {
  @include grid-container;

 // this will keep our element__inner in the container by adding padding as soon as the page is bigger then the container
  @media (min-width: 1200px) {
    padding: 0 calc((100% - 1200px) / 2);
  }

  element__inner {
    @include grid-column(12);
  }
}
```
