### ISSUE TITLE
I want to use omega(3n+1), but Neat disallows this. What's the alternative?

### ISSUE THREAD

**Issue by xaliber** [thoughtbot/neat#502]
My first div spans 12 columns while the next divs only spans 3 columns. Something like this:

http://i.stack.imgur.com/t8XRP.png

So I thought having omega(3n+1) to select the third div after the first one would be manageable. Turns out, as it's said in Neat documentation, composite argument such as 3n+1 is not supported.

I have tried `div:first-of-type ~ div { @include omega (3n); }` to select the third occurrence after the first div, but to no avail.

Any idea what's the alternative?

**Comment by nickngqs** [comment]
Are you using Neat 2.0?

If yes, I believe they have removed the omega. You should try to do this instead.

`<div class='featured-image'></div>
 <div class='standard-image'></div>
 <div class='standard-image'></div>
 <div class='standard-image'></div>
`

`
.featured-image { @include grid-column(12) }
.standard-image { @include grid-column(3) }
`

**Comment by xaliber** [comment]
Still 1.8 I believe. It's a part of the WordPress theme framework: [Bourbony Sage](https://github.com/smutek/BourbonySage) (Sage + Bourbon + Neat).

Omega works fine in another instance (e.g. `omega (3n)`) but with the composite argument it comes into trouble.

**Comment by xaliber** [comment]
This is a hack I've been considering (adding two hidden divs after the first) http://jsfiddle.net/61kchdn8/ so it will correctly select `3n+1`. But it's very hacky.

**Comment by lextoc** [comment]
I've also got certain columns with a span of 3, and some with a span of 6. Is their a correct way to remove the gutter margin of those at the right side of the row?

**Comment by nickngqs** [comment]
If you guys are talking about 1.8.

Then just use normal css (nth-child selectors) to achieve that.

Since essentially what omega does is give the last column on the row margin: 0 and clearing left for the next column so that the column will move down the next row.

And if you guys are doing nth-child selectors in a responsive setting. Remember to declare it using the media splitting method, since whatever you declare on nth-child selectors will be bring forward to the next breakpoint.

or Read this -> [FAQ](https://github.com/thoughtbot/neat#faq)

**Comment by lextoc** [comment]
@nickngqs: thanks for the suggestion. Alas... my content is dynamic, therefore I cannot know which nth child will need the omega.

**Comment by nickngqs** [comment]
@lextoc when you say dynamic, do you mean like all your column span could be 3 or 6 in dynamic sequence, meaning there is no pattern at all

**Comment by lextoc** [comment]
@nickngqs Indeed, there is no pattern at all. There can be x columns with either 3 or 6 column span.

**Comment by nickngqs** [comment]
Then I believe that it would more viable using js

**Comment by lextoc** [comment]
@nickngqs I believe I'll have to remove the semantic part of this framework in case I want to use JavaScript to calculate which column is at the right side of the row. :(

**Comment by danethomas** [comment]
@nickngqs and in v2 this should just work already right?

I'm running into an issue at a certain breakpoints using this code:

```
.footer-nav {
  @include grid-container;
  margin-bottom: 5em;

  & > li {
    @include grid-column(12);
    margin-bottom: 2em;

    @include grid-media($neat-grid-tablet) {
      @include grid-column(6);
    }

    @include grid-media($neat-grid-desktop) {
      @include grid-column(3);
    }
  }
}
```

In the ``$neat-grid-tablet`` breakpoint the second column's content is shorter than the first, so the 3rd column falls under the second rather than 'clearing' and starting from the left of the container.

Obviously I could target this column within the ``grid-media()`` breakpoint but is this something that Neat should be handling out of the box or something you have a recommendation for?

![screen shot 2016-10-20 at 12 59 49 pm](https://cloud.githubusercontent.com/assets/80384/19543694/20f3cb9a-96c5-11e6-8fe9-d94d37847878.png)

**Comment by nickngqs** [comment]
Hey! I actually using Neat 2.0 for my latest project and yup i ran into this problem as well. Everything collapse properly when all of them is the same height. But if one of them is on a different height, then yes, this would happen and you will have to clear them.

And i do believe the guys working on Neat is avoiding using nth-child selectors so that it not handle out of the box. (But i do believe keeping the mixins as clean as possible is great, so clearing is actually controlled by the developer)

And please use media splitting to clear the floats :) speaking from experience.

**Comment by danethomas** [comment]
Interesting @nickngqs and apologies I actually thought you were part of the Thoughtbot / Neat team. I still would be keen to hear their thoughts on this. 

In terms of media splitting, how are you currently achieving this in your new project? Are you just using regular media queries and putting your ``@include grid-media`` mixins within that? 

It seems like this is something that the ``grid-media`` mixing could support down the track? Also keen to hear the Neat teams view on this as well.

**Comment by nickngqs** [comment]
I knew it, thats why I added 'the guys working on Neat' :)

Anyway, currently I feel the grid-media is pretty underwhelming to use.

So right now I do something like this
```
$s-bp  : 544px
$m-bp  : 768px
$l-bp  : 1024px
$xl-bp : 1200px

$s  : "(min-width: #{$s-bp}) and (max-width: #{$m-bp - 1px})"
$m  : "(min-width: #{$m-bp}) and (max-width: #{$l-bp - 1px})"
$l  : "(min-width: #{$l-bp}) and (max-width: #{$xl-bp - 1px})"
$xl : "(min-width: #{$xl-bp})"

$s-up  : "(min-width: #{$s-bp})"
$m-up  : "(min-width: #{$m-bp})"
$l-up  : "(min-width: #{$l-bp})"
$xl-up : "(min-width: #{$xl-bp})"
```

I then use SASS @media depending on how I need them. I use mobile first approach and work up the screens. So I'll use 

```
@media #{$s-up}
    +grid-column(12)

@media #{$m-up}
    +grid-column(4)
```

However, with nth-child selectors since if you do the mobile first approach, the nth-selectors will be bring forward to the next breakpoint as well. And then you'll have to keep overriding something like nth-child(2n): margin-bottom: none;

But that's bad.

So I'll make sure the nth-selectors are only happening within the grid range like this

```
@media #{$s}
    &:nth-child(2n)
        margin-bottom: 25px
```
