### ISSUE TITLE
2.0 needs improved docs for `grid-media`

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#530]
This is the current description of the `grid-media()` mixin.

> Creates a media query in which custom grid properties can be defined. Add the media property to your custom grid settings map and add the media you would like to scope to. If only a number is defined, it is assumed this is a min-with value. Your custom grid can then be passed to the mixin.

This does not explain that one can:
- use `max-width` mq's
- use `print` mq's
- use complex mq's

**Comment by tysongach** [comment]
It’d be worth mentioning that, out of the box, Neat comes with an opinion that your workflow is mobile-first. You can do a large-screen-first workflow, but it requires a more verbose implementation and you cannot globally tell Neat to work that way.

**Comment by kgcreative** [comment]
I have a mq implementation I've been using instead of neat's, mostly because I didn't quite parse neat's mq implementation. I would love to be able to not do

```@include mq($custom-breakpoint) {
  @include grid-column(3);
}```

If I can use neats implementation out of the box for min/max, max, min or print MQ's, especially in the context of being able to also define custom gutters, then I'd switch in a heartbeat. Sounds like you already support all the features I need out of the box

**Comment by whmii** [comment]
done
