### ISSUE TITLE
What should be the default of custom grids?

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#533]
Currently, the default grid properties are as follows:

```
$_neat-grid-defaults: (
  columns: 12,
  gutter: 20px,
  media: null,
  color: rgba(#00d4ff, 0.25),
  direction: ltr,
);
```

Any time a mixin is called with the a custom grid (see: http://neat.netlify.com/docs/latest/#custom-grids), any properties undefined in the grid will default to the properties of `$_neat-grid-defaults`. 

## Currently  
Any property left undefined in the custom grid map that you have passed in to the grid mixin you are using, will default-to/inherit-from `$_neat-grid-defaults`

`$my-custom-grid` → falls back to → `$_neat-grid-defaults` 

## Potentail Change
This functionality could be changed so that instead, any property left undefined in the custom grid map will default-to/inherit-from the globally defined `$neat-grid`, which in tern defaults-to/inherits-from `$_neat-grid-defaults`.  Since the merge operation described in https://github.com/thoughtbot/neat/issues/531 is not done until the mixin/function is run, it would not matter in what order the various grids were defined. This functionality may be more intuitive.

`$my-custom-grid` → falls back to → `$neat-grid` → falls back to → `$_neat-grid-defaults` 

This change would mean that we are pulling in globally defined, user facing variables in to private functions, which makes me nervous.

---

This is a sister issue to https://github.com/thoughtbot/neat/issues/532

**Comment by kgcreative** [comment]
I've tended to define global variables outside functions with `!default` flags, then map those to private variables inside a function. That means that as long as I declare them before importing, it maintains inheritance in source order. I'm already used to importing '_neat-settings` before importing `neat, so that convention seems robust to me.

I'm always nervous to pull in global variables defined outside of order since I don't know what exact effect that may have on my code base, so I prefer to know any `$variable: value`; will override previously set values, while `$variable: value !default`; will have the opposite effect.

In fact, I depend on this convention when declaring variables in modules, since that way I know there will be generic styling if that module is copied out of the framework and on it's own, which allows other developers to import modules to their own projects without having to re-write the module code, they can just declare new variables in whatever their variables convention is.

**Comment by kgcreative** [comment]
Fwiw, Having had a bit more time to parse this, conceptually I really like the `$my-custom-grid` → `$neat-grid` → `$_neat-grid-defaults` fallback model. It means I don't have to re define properties on a custom grid if  i only want to modify one or two values.

**Comment by whmii** [comment]
💥
