### ISSUE TITLE
'grid-column', 'grid-media' combination should be more DRY

### ISSUE THREAD

**Issue by cewen** [thoughtbot/neat#540]
How can I get `.item` to inherit the correct width/gutter for 1 column on all of my established breakpoints (each with a custom grid) without having to repeat `grid-media` and `grid-column(1)` for each? It seems like this repetition should be unnecessary.

Custom grid settings and `.item` code below:

    $neat-grid: (
      columns: 12,
      gutter: 2%
    );

    $grid-m: (
      columns: 12,
      gutter: 4%
      media: 760px
    );

    $grid-l: (
      columns: 12,
      gutter: 40px,
      media: 1000px
    );

    .item {
      @include grid-column(1);

      @include grid-media($grid-m) {
        @include grid-column(1);
      }

      @include grid-media($grid-l) {
        @include grid-column(1);
      }
    }

**Comment by whmii** [comment]
I think the example code you have pasted above is perfectly acceptable. You are defining 3 different sizes at 3 different breakpoints. These issues would only come in to play for projects with lots of different gutter sizes across screen sizes.

A way this could be handled is with a mixin containing a loop that iterates through all of the media queries you wanted.

**This is psudo-code** but given your example it would probably look something like:

```
@mixin my-custom-grid-column($columns) {
  @include grid-column($columns);
  $media-grids: $grid-m, $grid-l;
  @each $grid in $media-grids {
    @include grid-media($grid) {
      @include grid-column($columns);
    }
  }
}

// and then…

.item {
  @include my-custom-grid-column(1);
}
```

Speaking generally, shorter is not always better as a solution like the one outlined above can actually make it more difficult for others reading the code to easily grasp what is going on. 

Overall, this is the sort of thing that should probably be implemented manually on a per project basis, since the specific needs would be likely from project to project.
