### ISSUE TITLE
Edge Case: Neat 2.0 + flexbox + justify-content: center + orphan children

### ISSUE THREAD

**Issue by kgcreative** [thoughtbot/neat#543]
Background:
I'm trying to achieve an auto-centering layout. Prior to this, the best way to achieve this was through  nth-of-type and class wizardry. Primarily because i'd have to account for how many items exist, how many orphans, etc.

With Neat 2.0 + Flexbox, this is ALMOST solved.

The default neat grid allows for orphans to wrap left, and as I keep adding orphans, they automagically stack very nicely.
![neat default](https://cloud.githubusercontent.com/assets/3443142/23053553/4b65598e-f48f-11e6-994e-5d98ff2a3b01.png)

Adding Flexbox, this is even better, since it makes it so staggered grid-column items wrap without weird float issues. It's like adding an automagic clearfix every nth-of-type.
![plus flexbox](https://cloud.githubusercontent.com/assets/3443142/23053593/899ec1d6-f48f-11e6-965c-ace2ecbfeba2.png)

What I'm trying to achieve, then, is to extend this behavior further with flexbox, by adding `justify-content: center` to the parent container. This should, in theory, give me the result below.
![desired result](https://cloud.githubusercontent.com/assets/3443142/23053606/ac8e67f0-f48f-11e6-8135-74f439f91f52.png)

However, because neat calculates it's floated position with margin-left, the actual result is this:
![bug](https://cloud.githubusercontent.com/assets/3443142/23053634/ea61a024-f48f-11e6-8cfe-8726fb02f306.png)

My current workaround involves fetching the current custom grid, and adding margin-left and margin-right (half margins) to the the grid-column object, but obviously this gets extremely repetitive and feels very hacky.

The only solution that comes to mind is adding a `direction: center` to the grid-media() custom map, which would somehow trigger margins to change from `margin-left: $gutter`; to `margin-left: $gutter / 2` and `margin-right: $gutter / 2`, but that seems to have a lot of ramifications in terms of adding extra complexity to the grid.

thoughts?

**Comment by kgcreative** [comment]
As a workaround, I added the following to my `flex-container` mixin:

```
  @if ($_justify-content == center) and ($_grid == null) {
    $_gutter: _retrieve-neat-setting($neat-grid, gutter) / 2;
    @supports (display: flex) {
      transform: translateX(-$_gutter);
    }
  } @else if ($_justify-content == center) {
    $_gutter: _retrieve-neat-setting($_grid, gutter) / 2;
    @supports (display: flex) {
      transform: translateX(-$_gutter);
    }
  }
```
It's a little hacky, and definitely not DRY, but it's an ok workaround to the current behavior

**Comment by whmii** [comment]
Thank you for putting together such a comprehensive issue. It makes addressing it soooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo… oooooooooooooooooooo… ooo much easier.

So i thought I would be all clever ad be like "Aha, all you need to do is add padding to the container. Turns out if you do that it throws off all the percentage calculations 😭. 

  
![screen shot 2017-02-17 at 10 00 40 am](https://cloud.githubusercontent.com/assets/2489247/23070483/2bfe68e6-f4f9-11e6-943e-9921057ca6f2.png)

2nd option would be something like the following on the container…
```
  padding-right: $gutter;
  margin-left: -$gutter;
  width: calc(100% + $gutter);
```
but that would be more hacky than the transform…

I think the transform is ok, but you could also switch to relative positioning based on your needs.

The last way you could address this is with (i hate to say this…) nth child selectors here's an example of how this works:

```scss
$neat-grid: (
  columns: 12,
  gutter: 20px,
);

.grid {
  @include grid-container;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

.grid__column:nth-child(13),
.grid__column:last-child {
  margin-right: 20px;
}


.grid__column {
  @include grid-column(1);
}
```

![screen shot 2017-02-17 at 10 23 51 am](https://cloud.githubusercontent.com/assets/2489247/23071164/7340afc8-f4fb-11e6-9ec1-468ef79622d6.png)

This creates a margin right on the last object in the row and the last object in the container which causes the flexbox to self correct. 

Deciding which of the 3 solutions to use depends on your needs but unfortunately I dont see a way to include this in to the framework itself.

**Comment by kgcreative** [comment]
Huh... the last solution feels a lot like an edge case `omega()` mixin. I might release that as a stand-alone enhancement for this use case, ala Josh Fry's `omega-reset()` for neat 1.x

**Comment by kgcreative** [comment]
Need to add some documentation, but https://github.com/kgcreative/neat-2.x-omega seems to solve the issue.

**Comment by whmii** [comment]
Nice work! fair warning, I think this is too specific a need to make it in the core library but it makes an awesome extension. 👍

**Comment by kgcreative** [comment]
https://github.com/kgcreative/neat-2.x-omega/blob/master/_omega.scss

I've updated the code, dried it up just a bit, and as I was experimenting with layouts, found another edge case where, in the case of non-flexbox floated layouts, if the last element is a row is shorter than the other elements, the float doesn't properly clear all the way.

I've ammended the omega mixin to also account for this behavior, essentially covering 2x edge cases in one.
