### ISSUE TITLE
No more media(size)?

### ISSUE THREAD

**Issue by TMcLoone** [thoughtbot/neat#552]
Hey guys, 

Super exciting to see 2.0, I've just started using it on a new project. With the old neat I would create specific media queries for certain elements that would break at different points. i.e. media(439px), it seems the only way to do this now is to create a totally new grid each time. Is that right? If so, that's quite cumbersome, it would be really nice not to have to do that or use a different mixin for media queries. 

I like that you've taken the simplistic approach to 2.0 but missing certain things already, perhaps there could be an 'on the rocks' version of neat with some additional mixins.

**Comment by kgcreative** [comment]
You can use vanilla media queries if you just need breakpoint behavior. The grid-media mixin is there for everything else.

Keep in mind the way custom neat grids inherits their values makes it so you only need to give it the properties that differ from the default grid.

```
$my-custom-grid: (
  media: 439px,
);
```

Is a perfectly acceptable use case.

**Comment by TMcLoone** [comment]
I guess so, code just looks a little messy now with handling the different kinds of media queries. It would be nice if the grid-mixin could default to a simple vanilla media query if only a value is supplied

**Comment by kgcreative** [comment]
It takes a bit more discipline to set up a consistent set of custom maps. 

What made it click for me is thinking of grid-media not as a custom grid, but as a custom media query that allows me to /modify/ the neat grid.

Once I figured that out, then I just set up one custom grid per media query. That means that `@include grid-media($media-query) { @content }` pretty much replaces `@include media() {}` and vanilla media queries.

I found for me, a lot of the breakpoint adjustments when dealing with grid objects also lined up with gutter width changes, so that made using grid-media instead of media queries pretty compelling.

**Comment by whmii** [comment]
@TMcLoone I think If i was working through this personally I would probably just use a regular media query,

**However**

One thing that would probably fit your needs is the fact that when you can skip the step of defining a 'new grid' by just passing a map directly in to the mixin. I double-checked and the code below functions correctly and do exactly what you described above in just a couple more words.

```
@include grid-media((media:439px)) {
    …
}
```

I have a mixin, I have a map… AH mixin-map-mediaquery!

**Comment by kgcreative** [comment]
@whmii it hadn't even occurred to me that you could define a map on the fly without assigning it to a variable. 💥

**Comment by TMcLoone** [comment]
OH, that’s cool you can do a map like that!

I think I’ll just make my own mini mixin for media queries and only use grid-media if I need to change the actual grid.

**Comment by whmii** [comment]
Closing for now. Feel free to re-open if you have any further questions.

**Comment by gitsilvan** [comment]
I am still a bit puzzled about how to use vanilla media queries and grid-media together. Before I did something like this


```
$medium: new-breakpoint(min-width 768px);

.box {
    @include span-columns(6);
    font-size: 1em;

    @include media($medium) {
        @include span-columns(12);
        font-size: 2em;
    }
}
```

I put grid and content styling into one media query. Apparently this was not how the media mixin was supposed to be used, but it worked. 

So now, in order to do it "correctly" and seperate grid and content styling, I would have to do something like this:

```
$medium-grid: (
  media: 768px
);

.box {
    @include grid-column(6);
    font-size: 1em;

    @include grid-media($medium-grid) {
        @include span-columns(12);
    }

    @media screen and (min-width: 768px) {
        font-size: 2em;
    }
}
```

Correct?

**Comment by whmii** [comment]
yes but you can collapse it down to the following.

```scss
$medium-grid: (
  media: 768px
);

.box {
  @include grid-column(6);
  font-size: 1em;

  @include grid-media($medium-grid) {
    @include grid-column(12);
    font-size: 2em;
  }
}
```

**Comment by whmii** [comment]
And if you wanted to make your own mixin for this it might be something like…

```scss
@mixin media-medium() {
  @include grid-media((media: 768px)) {
    @content;
  }
}
```

**Comment by gitsilvan** [comment]
Great, so I can basically use it as before. Thank you!
