### ISSUE TITLE
Deep links for features on the docs page should update url

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#566]
> The javascript for this prevents default, so the page URL is never updated, ex docs/latest/#grid-push.
> 
> Having never done this previously, I'm going to have to do some research.

---
Ported over due to https://github.com/thoughtbot/neat/issues/561
Originally appeared on https://github.com/thoughtbot/neat.bourbon.io/

**Comment by tysongach** [comment]
As discussed IRL, I felt that using links within the documentation nav should _not_ update the URL, because that would be captured in the browser’s history and using the back button would go through each hash. I find that confusing.

An alternative approach could be to offer an easier way to copy the link/hash to a direct documented item.
