### ISSUE TITLE
Add blog post resources… somewhere

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#574]
There are 2 posts on the thoughtbot blog that go in to great detail on Neat 2.0, how it works, and how to use it.

These should be linked somewhere, be it the README or the site or both.

**Comment by wardpenney** [comment]
@whmii I vote README

**Comment by burmashave** [comment]
These are very helpful posts, but they could use some editing.

"straight forward to maintain" -> "straightforward"

"have the gutters on exterior" -> "on the exterior"

"The interface for using these mixins has also been standardize across all of them" -> "standardized"

"Here’s the default values and what this’ll look like code." -> "in code"?

"Because of the way the grade calculated Neat 2.0 supports a lot of different options for these gutter values." -> a dependent clause in search of an independent one

"You can define your own grid maps and pass them directly in to the second argument of the mixin follows." -> "as follows"?

etc.

etc.

**Comment by whmii** [comment]
Added in https://github.com/thoughtbot/neat/commit/e361e1e18218b56d3e16562f20f0e0ee0ddf1873
