### ISSUE TITLE
confusion about removing inner gutters

### ISSUE THREAD

**Issue by hendrikeng** [thoughtbot/neat#602]
hey there i just started using neat coming from susy, i am a bit confused how i would remove the inner gutters but keep the outer once.

i created a costum grid  for a section with no gutters: 

```
$no-gutter-grid: (
  columns: 12,
  gutter: 0,
);

i cal it via:
section {
@include grid-column(4 of 12, $no-gutter-grid);
}
```

however, it would be better if the outter gutters still consist and only the inner once would be removed..is this possible?

my page is wrapped with 
```
.o-wrap {
  @include grid-container;
  @include grid-visual(pink);
  overflow-x: hidden;
}
```

to have my content wrapped in a max-width container i am using this mixins: 
https://github.com/thoughtbot/neat/issues/498 (works nicely) arround my content:

```
main {
  @include section-container(wide);
}

```

```

<div class="o-wrap">
  <main>
      <section>
      </section>
  </main>
</div>
```

thanks a lot and keep up the awesome work

**Comment by hendrikeng** [comment]
it seems i would have to wrap section with another gutter map like the default:

<wrap>
  <section>
  </section>
</wrap>

wrap {
  @include grid-column(12);
}

section {
  @include grid-column(4 of 12, $no-gutter-grid);
}

would that be the right approach ? 
thanks for ur help

**Comment by whmii** [comment]
Your example above seems correct based on what you are trying to achieve, assuming this is what you are going for.

![3 boxes wrapped in another box](https://cloud.githubusercontent.com/assets/2489247/25315235/fe066fa6-281f-11e7-8dd0-d67d9a7e8575.png)

To be honest I think I would probably just write it using vanilla sass since no gutter grids dont realy *need* neat. This'd look something like

```
section {
  float: left;
  width: percentage(1/3);
}
```

but honestly either way would be fine.

**Comment by hendrikeng** [comment]
thanks a lot :)
