### ISSUE TITLE
calc( + ) neat minification error

### ISSUE THREAD

**Issue by rollrodrig** [thoughtbot/neat#607]
This an example that works fine
    margin-left: calc(33.33333% + 0px);

But the compressor remove extra spaces
    margin-left: calc(33.33333%+0px);
And this becomes as invalid css

Temporary fix. I modified inside neat folder every mixin

For example
width: calc(100% + #{($_grid-gutter * 2)});
To 
width: calc(100% - -#{($_grid-gutter * 2)});

It fix the problem when the css is monified

Any idea.

**Comment by whmii** [comment]
What compressor/minifier are you using?

**Comment by rollrodrig** [comment]
I am running sass with gulp. The compressor is "liferay css compressor" is the cms automatic compressor.

**Comment by kgcreative** [comment]
I did a quick search if this issue and it seems just about every CSS compressor has run afoul and had to fix this issue. The CSS spec calls for spaces between math operators in calc, which means compressors need to not strip whitespace inside those operations. Unfortunately, the issue here is not with Neat, but with liferay

**Comment by rollrodrig** [comment]
Yeah i know. The issue is not with neat. It is only with every compressor.

**Comment by kgcreative** [comment]
Both cssmin and postCSS with cssnano properly compress calc functions. I've had no issue with either on my pipeline

**Comment by whmii** [comment]
Seems like this is simply not an issue with Neat. Closing
