### ISSUE TITLE
windows has problem with to long path cause of dependencies in public\node_modules

### ISSUE THREAD

**Issue by agentschmitt** [thoughtbot/neat#610]
When add bourbon-neat 2.0.0 to the node_modules of my project i get an problem with my build tool (Visual Studio 2015 in Windows 10) cause of to long pathes.
After looking in your library i found out that the folder \bourbon-neat\public\node_modules is causing this issue. Especially the gulp modules cause they have node_modules subfolders again.

Is it possible to exclude this dependies from your publish process?
Or is there any other solution?

**Comment by tysongach** [comment]
Hi @agentschmitt! Neat [does not have any `dependencies` in its `package.json`](https://github.com/thoughtbot/neat/blob/master/package.json), so it shouldn’t contain a `node_modules` directory, at all. I also ran a fresh `npm install neat` on my machine and see no `node_modules` directory. Perhaps something else in your build chain is causing the error?

**Comment by agentschmitt** [comment]
Hi tysongach,

you are right there are no dependencies in package.json but there are dependencies in your public folder.

After adding the package with npm install bourbon-neat i have looked in the node_modules\bourbon-neat folder and there is an subfolder public\node_modules which contains some other packages:
bourbon
gulp
gulp-autoprefixer
gulp-connect
gulp-sass
node-bourbon
node-sass

![image](https://user-images.githubusercontent.com/13732585/27530498-423b3c36-5a59-11e7-8982-98d5d50800ba.png)

**Comment by kwiss** [comment]
+1

**Comment by tysongach** [comment]
Interesting. I am able to re-produce this locally now. I’m not sure why this is causing issues with your build tool, though. 

That `public/` directory appears to contain a mashup of the files to our old website and files for our current [contributing page](https://github.com/thoughtbot/neat/blob/master/contrib/index.html), but I don’t no why that is part of the Neat npm package. My hunch is that someone had our old Jekyll website in a “built” state inside a `public/` directory, and since we have `public/` in our `gitignore` file, that person didn’t notice all of those website files via Git. But we don’t have `public/` in our `.npmignore`, so if that person ran `npm publish`, `public/` likely got accidentally bundled along with it.

This has prompted me to update our `.npmignore` in https://github.com/thoughtbot/neat/pull/613. I think we’ll just need to publish an updated npm package to make it go away. To test, I packaged Neat locally with `npm pack` and I didn’t see a `public/` directory within it. We also no longer house our website within this repo, so the problem should go away completely.

**Comment by agentschmitt** [comment]
Thx this will fix my problem.
Will just have to wait for the next npm release of neat ;)

**Comment by tysongach** [comment]
@agentschmitt I just cut Neat 2.1, which includes changes that should mean we no longer are publishing that `public` directory inside our npm package.
