### ISSUE TITLE
node-sass - retrieve-neat-settings.scss - map-merge error

### ISSUE THREAD

**Issue by quepaso** [thoughtbot/neat#630]
Hola,
sorry if that issue should rather go to stackoverflow. Am trying to migrate a laravel project from bootstrap to bourbon and I'd really like to get it running and do something that doesn't look like bootstrap.

Using:
Webpack: 3.5.5
Node-Sass: 4.5.3
Node.js: v8.4.0
Bourbon neat: 2.1.0
OS: Windows 10 (wamp)
... basically everything's up to date.

When doing my npm run ... I'm getting an error: "Module build failed: Argument '$map2' of 'map-merge($map1, $map2)' must be a map". Backtrace to bourbon-neat/core/neat/functions/_retrieve-neat-settings.scss:17:  $_grid-settings: map-merge(_neat-merge-defaults($neat-grid), $grid);

Any idea what to look for?

**Comment by quepaso** [comment]
Hh, well in the very second that I posted that I had an idea. The issue is not a bug. It's the user, as usual. Problem solved.

**Comment by shennan** [comment]
@quepaso Can you elaborate on what the mistake was? I'm having the same issue. All information is useful.

**Comment by shennan** [comment]
For anyone experiencing the same kind of error, here's how I solved:

I was migrating from *bourbon-neat@1.7* to *bourbon-neat@2.1*, and had done a batch find-and-replace for some of the methods. It turns out that a few of my old `span-columns` had a second argument of `border-collapse` a là:

```
@include span-columns(4, border-collapse);
```

Which my batch find-and-replace turned to:

```
@include grid-column(4, border-collapse);
```

Which are bad arguments for *bourbon-neat@2.1*. Removing the `border-collapse` argument solved the issue.

**Comment by whmii** [comment]
For future peeps: Any time a gird map is used in a mixin, the private function `_retrieve-neat-settings` is used to merge the grid passed in to the mixin with the library default grid (aka `$neat-grid`). You can experience an error like the one above when something that isn't a map is passed in to the mixin. Sass tries to preform a `merge` which can only be preformed with 2 maps and errors out. 🎩 🐙
