### ISSUE TITLE
During precompile (local and heroku) Undefined mixin 'box-sizing'

### ISSUE THREAD

**Issue by joemsak** [thoughtbot/neat#93]
Line 3  neat/app/assets/stylesheets/grid/_grid.scss

Here is the trace on heroku deploy
https://gist.github.com/joemsak/71f8591c93fd911cb948

**Comment by igorspasic** [comment]
This is a showstopper for me, seems a valid issue. Response from gulp and gulp-ruby-sass:
```
[19:16:15] gulp-ruby-sass stderr: Error: Undefined mixin 'box-sizing'.
        on line 5 of scss/neat/grid/_box-sizing.scss, in `box-sizing'
        from line 5 of scss/neat/grid/_box-sizing.scss
        from line 11 of scss/neat/_neat.scss
        from line 5 of scss/main.scss
```

**Comment by mcrider** [comment]
Yes it looks like box-sizing was removed from bourbon and a release was recently made; A new release of neat should fix this issue?

In the meantime, putting the precompile regex from @phy5ics in application.rb seems to have solved what was breaking my deploys.

**Comment by tysongach** [comment]
@igorspasic @mcrider When we deprecated the `box-sizing` mixin in Bourbon, we also removed it from Neat in [this commit](https://github.com/thoughtbot/neat/commit/60dc0a38bcabe3b9b1df056237a881590783083a). We also have yet to fully remove the `box-sizing` mixin from Bourbon; it’s simply been deprecated, given a warning and moved [here](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss).

What version of Bourbon and Neat are you using?

**Comment by mcrider** [comment]
I'm using bourbon (4.2.1) and neat (1.7.1).

**Comment by igorspasic** [comment]
Ok, got it on my side - it is defined in file with items that are going to be deprecated soon; for me everything works now. Ive just deleted that file :) sorry!

**Comment by tysongach** [comment]
@igorspasic Great. `box-sizing` doesn’t really need prefixes anymore, so you should be good to go.

**Comment by percyhanna** [comment]
In case someone else runs into this problem: we had migrated some Sass from another project that was not on Rails, into a Rails project. We started getting this error. The problem was that there was another `application.scss` file nested inside our style sheets folder. Example:

* `app/assets/stylesheets/application.scss`
* `app/assets/stylesheets/layout/application.scss`

The second file was being compiled by Rails automatically because it matched the default Regexp pattern of `application.scss`. However, this file was really just being imported by the primary/root `application.scss` file. Because of its name, it was getting compiled on its own, and therefore did not have `@import 'bourbon';` or `@import 'neat';` in that file, and failed when `@include box-sizing` was called.

So, we just renamed the file and it was fixed. Also, `box-sizing` is deprecated and will be removed in v5.

**Comment by jdtriska** [comment]
Just wanted to chime in here in case someone has this issue, but it isn't solved with the above comment by @percyhanna. We did in fact have an additional `application.css` file in our `app/assets/stylesheets` folder, deleted that, but still had the issue. As it turned out, inside our `app/config/initializers/assets.rb` file we had set the following line
```
Rails.application.config.assets.precompile << '*.css'
```
This caused rails to precompile *all* css files. We naively didn't think this was an issue, but it looks this causes a conflict with rails since it was already precompiling the `application.css.scss` file, and now we were asking it to do so again. This manifested in the "undefined mixin" error, as well as some "undefined sass variable" errors. We replaced the offending line, specifying the subfolders to precompile like so
```
`Rails.application.config.assets.precompile << 'common/*.css'`
```
This fixed the issue.
